var routes_schema = {
  "fields":[
     {
        "name":"OBJECTID",
        "type":"esriFieldTypeOID",
        "alias":"OBJECTID",
        "editable":false,
        "nullable":false,
        "defaultValue":null,
        "description":null,
        "domain":null
     },
     {
        "name":"FacilityID",
        "type":"esriFieldTypeInteger",
        "alias":"Kjøretøys-ID",
        "editable":true,
        "nullable":true,
        "defaultValue":null,
        "description":null,
        "domain":null
     },
     {
        "name":"FacilityRank",
        "type":"esriFieldTypeInteger",
        "alias":"Rekkefølge",
        "editable":true,
        "nullable":true,
        "defaultValue":null,
        "description":null,
        "domain":null
     },
     {
        "name":"Name",
        "type":"esriFieldTypeString",
        "alias":"Rutenavn",
        "length":255,
        "editable":true,
        "nullable":true,
        "defaultValue":null,
        "description":null,
        "domain":null
     },
     {
        "name":"IncidentCurbApproach",
        "type":"esriFieldTypeSmallInteger",
        "alias":"Ankomstside",
        "editable":true,
        "nullable":true,
        "defaultValue":null,
        "description":null,
        "domain":null
     },
     {
        "name":"FacilityCurbApproach",
        "type":"esriFieldTypeSmallInteger",
        "alias":"Avreiseside",
        "editable":true,
        "nullable":true,
        "defaultValue":null,
        "description":null,
        "domain":null
     },
     {
        "name":"IncidentID",
        "type":"esriFieldTypeInteger",
        "alias":"Hendelses-ID",
        "editable":true,
        "nullable":true,
        "defaultValue":null,
        "description":null,
        "domain":null
     },
     {
        "name":"StartTime",
        "type":"esriFieldTypeDate",
        "alias":"Avreisetidspunkt",
        "length":8,
        "editable":true,
        "nullable":true,
        "defaultValue":null,
        "description":null,
        "domain":null
     },
     {
        "name":"EndTime",
        "type":"esriFieldTypeDate",
        "alias":"Ankomsttidspunkt",
        "length":8,
        "editable":true,
        "nullable":true,
        "defaultValue":null,
        "description":null,
        "domain":null
     },
     {
        "name":"StartTimeUTC",
        "type":"esriFieldTypeDate",
        "alias":"Avreisetidspunkt, UTC",
        "length":8,
        "editable":true,
        "nullable":true,
        "defaultValue":null,
        "description":null,
        "domain":null
     },
     {
        "name":"EndTimeUTC",
        "type":"esriFieldTypeDate",
        "alias":"Ankomsttidspunkt, UTC",
        "length":8,
        "editable":true,
        "nullable":true,
        "defaultValue":null,
        "description":null,
        "domain":null
     },
     {
        "name":"Total_Minutes",
        "type":"esriFieldTypeDouble",
        "alias":"Kjøretid",
        "editable":true,
        "nullable":true,
        "defaultValue":null,
        "description":null,
        "domain":null
     },
     {
        "name":"Total_TravelTime",
        "type":"esriFieldTypeDouble",
        "alias":"Reisetid",
        "editable":true,
        "nullable":true,
        "defaultValue":null,
        "description":null,
        "domain":null
     },
     {
        "name":"Total_Miles",
        "type":"esriFieldTypeDouble",
        "alias":"Antall miles",
        "editable":true,
        "nullable":true,
        "defaultValue":null,
        "description":null,
        "domain":null
     },
     {
        "name":"Total_Kilometers",
        "type":"esriFieldTypeDouble",
        "alias":"Antall km",
        "editable":true,
        "nullable":true,
        "defaultValue":null,
        "description":null,
        "domain":null
     },
     {
        "name":"Total_TimeAt1KPH",
        "type":"esriFieldTypeDouble",
        "alias":"Reisetid i 1 km/h",
        "editable":true,
        "nullable":true,
        "defaultValue":null,
        "description":null,
        "domain":null
     },
     {
        "name":"Total_WalkTime",
        "type":"esriFieldTypeDouble",
        "alias":"Gangtid",
        "editable":true,
        "nullable":true,
        "defaultValue":null,
        "description":null,
        "domain":null
     },
     {
        "name":"Total_TruckMinutes",
        "type":"esriFieldTypeDouble",
        "alias":"Kjøretid, lastebil",
        "editable":true,
        "nullable":true,
        "defaultValue":null,
        "description":null,
        "domain":null
     },
     {
        "name":"Total_TruckTravelTime",
        "type":"esriFieldTypeDouble",
        "alias":"Reisetid, lastebil",
        "editable":true,
        "nullable":true,
        "defaultValue":null,
        "description":null,
        "domain":null
     },
    
  ],
  "geometryType":"esriGeometryPolyline",
  "sr":{
     "wkid":25833,
     "latestWkid":25833
  }
}