const urlFacilities = "https://demo01.geodata.no/arcgis/rest/services/GeoTek/Ambulanser/FeatureServer/0/query?where=status='Ledig'&f=json&outFields=Name";
const urlIncidents = "https://services.arcgis.com/2JyTvMWQSnM2Vi8q/arcgis/rest/services/AMK_hendelser/FeatureServer/0/query?where=1%3D1&returnGeometry=true&f=json&outFields=Name";
const urlPolygonBarriers = "https://services.arcgis.com/2JyTvMWQSnM2Vi8q/arcgis/rest/services/AMK_barriers/FeatureServer/2/query?where=1%3D1&returnGeometry=true&f=json&outFields=*";
const urlGPSimulator = "https://demo09.geodata.no/arcgis/rest/services/AMKSimulatorTjeneste/GPServer/AMK%20Simulator%20Script";
const urlGPPlume = "https://demo01.geodata.no/arcgis/rest/services/GP_Tjenester/CBRNE_Tool/GPServer/PlumeTool";
const urlGPRoadBlock = "https://demo01.geodata.no/arcgis/rest/services/GeoTek/Veisperringer_GP/GPServer/Veisperringer";
const urlGPHeli = "https://demo04.geodata.no/arcgis/rest/services/FinnRedningstid/GPServer/Finn%20redningstid%20for%20luftambulansen";
const urlGPRIndex = "https://demo01.geodata.no/arcgis/rest/services/AMK/BeredskapsindeksGP/GPServer/Beredskapsindeks";
const urlAppMissing = "https://testkommune.maps.arcgis.com/apps/webappviewer/index.html?id=32082b2392d3401a8083c8f9248e817f";
